### ISSUE TITLE
The bundle is large comparing to jsep + expression-eval

### ISSUE THREAD

**Issue by eight04** [ianchi/ESpression#1]
https://github.com/eight04/espression-bundle
https://github.com/eight04/expression-eval-bundle

| filename\library | espression | expression-eval |
|------------------|-----------------|------------|
| .js              | 55KB            | 24KB       |
| .min.js          | 28KB            | 7KB        |

BTW, what I need is jsep with regexp literal. Should I just use https://github.com/soney/jsep/pull/78 instead?

**Comment by ianchi** [comment]
Hi @eight04 
ESpression is indeed larger, because it adds more functionality, and because is written in Typescript, which is a little less minifyable (but gives more gziped ratio).

On one side, to compare with jsep, you should use `jsepParserFactory` to be fair. This alone reduces arround 10k the minified bundle.

If you serve gziped versions of your app, the difference is much less, because, as stated above, it gives better compression ratio:

**expression-eval**: 2.5kb .min.gz
**ESpression** (jsep preset + regex): 5.7kb .min.gz


Finally, if you only need jsep parser features + RegExp, you can use a custom parser based on the jsep rules:

```
export { es5EvalFactory } from "espression";
import { jsepRules, Parser } from "espression";
import { RegexRule } from "espression/rules";

const rules = jsepRules();
rules[rules.length - 1].push(new RegexRule());

export const jsepParser = new Parser(rules);
```
Mind that you have to update to v0.1.2, where I fixed a bug with direct imports of rules.
